---
- hosts: all
  vars:
    - default_app_name: osp_app
    - database_name: osp_app
    - database_user: postgres
    - backup_filename: "backup-{{ inventory_hostname }}_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.tar.gz"

  tasks:
    - name: Backup database and store file to tmp directory
      shell: "pg_dump -Fp -c -Z 9 {{ database_name }} > /tmp/{{ backup_filename }}"

    - name: store tempdir 
      set_fact:
       backup_file: "/tmp/{{ backup_filename }}"

    - name: Set app_name
      set_fact:
       app_name: "{{ app_name | default(default_app_name) }}"

    - name: Transfer database to host
      fetch:
        src: "{{ backup_file }}"
        dest: "/tmp/{{ app_name }}"

    - name: store tempdir
      set_fact:
       backup_file: "/tmp{{ app_name }}"

    - name: create db (will not fail if not exist)
      command: "createdb {{ app_name }}"
      become_user: database_user
      ignore_errors: yes 
      no_log: True

    - name: Import database
      shell: "gunzip < {{ backup_file }}| psql {{ app_name }}"
      become_user: database_user

    - debug:
       msg: The database application {{ app_name }} has been updated.
