---
- hosts: all
  remote_user: mako
  vars:
    backup_filename: "backup-$(date +%Y-%m-%d_%H-%M-%S)"
    osp_app_dir: "/home/{{ ansible_ssh_user }}/osp-app"
    db_name: "osp_app"

  tasks:
    - name: Backup osp app
      block:
        - name: Create temp directory
          tempfile:
            state: directory
          register: tempfile

        - name: store tempdir
          set_fact:
            tempdir: "{{ tempfile.path }}"

        - name: Copy osp app to tmp directory
          copy:
            src: "{{ osp_app_dir }}"
            dest: "{{ tempdir }}"
            remote_src: yes

        - name: Dump database to tmp directory
          postgresql_db:
            name: "{{ db_name }}"
            state: dump
            target: "{{ tempdir }}/{{ db_name }}.sql.gz"

        - name: Make archive
          archive:
            path:
              - "{{ tempdir }}/osp-app"
              - "{{ tempdir }}/{{ db_name }}.sql.gz"
            dest: "{{ tempdir }}/backup_filename"
          register: archive

        - name: store backup root path
            set_fact:
              backup_path: "{{ archive.arcroot }}"

        - name: Copy archive to remote
          debug:
            msg: Hello, world!

        - name: Remove temp dir
          debug:
            msg: Hello, world!
