---
- hosts: all
  remote_user: mako
  vars:
    backup_filename: "backup-$(date +%Y-%m-%d_%H-%M-%S)"
    osp_app_dir: "/home/{{ ansible_ssh_user }}/osp-app"

  tasks:
    - name: Backup osp app
      block:
        - name: Create temp directory
          tempfile:
            state: directory
          register: tempfile
        - name: store tempdir
          set_fact:
            tempdir: "{{ tempfile }}"
        - name: Copy osp app to tmp directory
          copy:
            src: "{{ osp_app_dir }}"
            dest: "{{ tempdir.path }}"
        - name: Dump database to tmp directory
          debug:
            msg: Hello, world!
        - name: Make archive
          debug:
            msg: Hello, world!
        - name: Copy archive to remote
          debug:
            msg: Hello, world!
