---
- hosts: all
  remote_user: mako
  vars:
    - tmp: "tmp"

  tasks:
    - name: Backup database and store file to tmp directory
      command: pg_dump -Fp -c -Z 9 'osp_app' > "osp_app-$(date +%Y%m%d%H%M%S).sql.gz"

    - name: Transfer database to host
      fetch:
        src: /home/mako/pg_dump/osp_app-*.gz
        dest: ~/

    - name: create db
      command: sudo su postgres - createdb sweetroll

    - name: Import database
      command: sudo su postgres - gunzip < sweetroll.sql.gz | psql sweetroll
