---
- hosts: all
  remote_user: mako

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
      become: yes
      become_user: root
      become_method: sudo

    - name: install nginx
      apt:
        name: nginx
        state: latest
      become: yes
      become_user: root
      become_method: sudo
