---
- hosts: all
  remote_user: mako

  tasks:
    - name: install dependencies
      block:
      - name: Update repositories cache
        apt:
          update_cache: yes

      - name: install nginx
        apt:
          name: nginx
          state: latest

      - name: install postgresql
        apt:
          name: postgresql
          state: latest
      become: yes
      become_user: root
      become_method: sudo
