---
- hosts: all
  remote_user: mako
  vars:
    temp_backup_directory: "/tmp/backup"
    backup_filename: "backup"
    osp_app_dir: "/home/{{ ansible_ssh_user }}/osp-app"
    db_name: "osp_app"

  tasks:
    - name: install prerequisites
      block:
        - name: Gather package facts
          package_facts:
            manager: apt

        - name: install dependancies
          apt:
            name: ["libpq-dev", "python-psycopg2"]
            state: latest
            update_cache: yes
          when: '"python-psycopg2" not in ansible_facts.packages'
      become: yes
      become_user: root
      become_method: sudo

    - name: Backup osp app
      block:
        - name: Create temp directory
          tempfile:
            state: directory
          register: tempfile

        - name: store tempdir
          set_fact:
            tempdir: "{{ tempfile.path }}"

        - name: Copy osp app to tmp directory
          command: cp -r "{{ osp_app_dir }}" "{{ tempdir }}"

        - name: Dump database to tmp directory
          postgresql_db:
            name: "{{ db_name }}"
            state: dump
            target: "{{ tempdir }}/{{ db_name }}.sql.gz"
            login_user: "{{ ansible_ssh_user }}"

        - name: Make archive
          archive:
            path:
              - "{{ tempdir }}/osp-app"
              - "{{ tempdir }}/{{ db_name }}.sql.gz"
            dest: "{{ tempdir }}/{{ backup_filename }}"
          register: archive

        - name: store backup root path
          set_fact:
            backup_path: "{{ archive.arcroot }}"

        - name: Copy archive to master
          fetch:
            src: "{{ archive.arcroot }}/{{ backup_filename }}"
            dest: "{{ temp_backup_directory }}/backup-{{ inventory_hostname }}/"

        - name: Remove temp dir
          file:
            state: absent
            path: "{{ tempdir }}"
