---
- hosts: all
  remote_user: mako
  vars:
    temp_backup_directory: "/tmp/backup"
    backup_directory: "/home/{{ ansible_ssh_user }}/backup/"

  tasks:
    - name: send backup directory to master
      copy:
        src: "{{ item }}"
        dest: "{{ backup_directory }}"
      with_fileglob:
        - "{{ temp_backup_directory }}/*"
      register: copy
      failed_when: "'Unable to find' in copy.stderr"

    - name: Remove backup dir
      file:
        state: absent
        path: "{{ temp_backup_directory }}"
      delegate_to: 127.0.0.1
