---
- hosts: all
  remote_user: mako
  vars:
    temp_backup_directory: "/temp"
    backup_directory: "/home/{{ ansible_ssh_user }}/backup/"

  tasks:
    - name: Find archive on /temp path
      local_action: command find /temp -name "*.gz"
      register: find

    - name: send backup directory to master
      copy:
        src: "{{ find.stdout }}"
        dest: "{{ backup_directory }}"

    - name: Remove backup dir
      file:
        state: absent
        path: "{{ temp_backup_directory }}"
      delegate_to: 127.0.0.1
